<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://web.cbr.ru/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DailyInfo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCursOnDateXMLResponse" namespace="http://web.cbr.ru/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DailyInfo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetCursOnDateXMLResponse" namespace="http://web.cbr.ru/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON JUL 15 21:14:52 GMT+04:00 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:GetCursOnDateXMLResponse>
         <ns0:EnumValutesXMLResult>
            <ns0:ValuteData>
               <xsl:for-each select="/ns0:GetCursOnDateXMLResponse/ns0:EnumValutesXMLResult/ValuteData/ValuteCursOnDate">
                  <ns0:ValuteCursOnDate>
                     <ns0:Vname>
                        <xsl:value-of select="Vname"/>
                     </ns0:Vname>
                     <ns0:Vcurs>
                        <xsl:value-of select="Vcurs"/>
                     </ns0:Vcurs>
                     <ns0:VchCode>
                        <xsl:value-of select="VchCode"/>
                     </ns0:VchCode>
                  </ns0:ValuteCursOnDate>
               </xsl:for-each>
            </ns0:ValuteData>
         </ns0:EnumValutesXMLResult>
      </ns0:GetCursOnDateXMLResponse>
   </xsl:template>
</xsl:stylesheet>
