<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:ns0="http://web.cbr.ru/" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" exclude-result-prefixes=" oracle-xsl-mapper xsi xsd xsl ns0 socket dvm mhdr oraxsl oraext xp20 xref"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DailyInfo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EnumValutesXMLResponse" namespace="http://web.cbr.ru/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/DailyInfo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EnumValutesXMLResponse" namespace="http://web.cbr.ru/"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.3.0(XSLT Build 170820.1700.2557) AT [MON JUL 15 15:49:49 GMT+04:00 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <ns0:EnumValutesXMLResponse>
         <ns0:EnumValutesXMLResult>
            <ns0:ValuteData>
               <xsl:for-each select="/ns0:EnumValutesXMLResponse/ns0:EnumValutesXMLResult/ValuteData/EnumValutes">
                  <ns0:EnumValutes>
                     <ns0:Vcode>
                        <xsl:value-of select="Vcode"/>
                     </ns0:Vcode>
                     <ns0:Vname>
                        <xsl:value-of select="Vname"/>
                     </ns0:Vname>
                     <ns0:VEngname>
                        <xsl:value-of select="VEngname"/>
                     </ns0:VEngname>
                     <ns0:Vnom>
                        <xsl:value-of select="Vnom"/>
                     </ns0:Vnom>
                     <ns0:VcommonCode>
                        <xsl:value-of select="VcommonCode"/>
                     </ns0:VcommonCode>
                     <ns0:VnumCode>
                        <xsl:value-of select="VnumCode"/>
                     </ns0:VnumCode>
                     <ns0:VcharCode>
                        <xsl:value-of select="VcharCode"/>
                     </ns0:VcharCode>
                  </ns0:EnumValutes>
               </xsl:for-each>
            </ns0:ValuteData>
         </ns0:EnumValutesXMLResult>
      </ns0:EnumValutesXMLResponse>
   </xsl:template>
</xsl:stylesheet>
