<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://speller.yandex.net/services/spellservice"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://speller.yandex.net/services/spellservice"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="YandexSpellerWebService">
        <plnk:role name="SpellServiceSoap" portType="tns:SpellServiceSoap"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://speller.yandex.net/services/spellservice" location="spellservice.wsdl"/>
</wsdl:definitions>
